collections:
  research:

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog_post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_pages"
    values:
      permalink: /pages/:basename:output_ext

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
